name: Build launcher

on:
  workflow_dispatch:
  push:
    branches: '*'

jobs:
  build:
    strategy:
      matrix:
        config:
        - name: Release
          lower: release
          
        - name: Debug
          lower: debug
          
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: gradle

    - name: Fix gradle permissions
      run: chmod +x ./gradlew

    - name: Build project
      run: |
        ./gradlew app:assemble${{ matrix.config.name }}"

    - name: Upload development build
      uses: actions/upload-artifact@v4
      with:
        name: geode-launcher-${{ matrix.config.lower }}
